[package]
name = "curso-gestion-de-servidores-rust"
version = "0.1.0"
authors = ["Yuliana <yulireyji@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
